version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pos_koi_image
    container_name: POS_KOI
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:...
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: POS_KOI_DATABASE
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: POS_KOI
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/POS_KOI.sql  # Mount file SQL ke MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: POS_KOI_PMA
    platform: linux/amd64
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
